# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='a', max_length=20, verbose_name='Account Status'),
        ),
    ]
