# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brewing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_date', models.DateField(default=django.utils.timezone.now)),
                ('packaged_beer_format', models.CharField(blank=True, choices=[('12oz/CS', '12oz/CS'), ('16oz/CS', '16oz/CS'), ('375ml/CS', '375ml/CS'), ('500ml/CS', '500ml/CS'), ('750ml/CS', '750ml/CS'), ('1/6bbl', '1/6bbl'), ('1/4bbl', '1/4bbl'), ('1/2bbl', '1/2bbl'), ('50l', '50l'), ('Firkin (10.8g)', 'Firkin (10.8g)'), ('Pin (5.4g)', 'Pin (5.4g)')], default='12oz/CS', max_length=20, verbose_name='Format')),
                ('packaged_quantity', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('packaged_beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewing.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Packaging Event',
            },
        ),
        migrations.CreateModel(
            name='PackagingFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Packaging Format',
            },
        ),
    ]
