# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('12oz/CS', '12oz/CS'), ('16oz/CS', '16oz/CS'), ('375ml/CS', '375ml/CS'), ('500ml/CS', '500ml/CS'), ('750ml/CS', '750ml/CS'), ('1/6bbl', '1/6bbl'), ('1/4bbl', '1/4bbl'), ('1/2bbl', '1/2bbl'), ('50l', '50l'), ('Firkin (10.8g)', 'Firkin (10.8g)'), ('Pin (5.4g)', 'Pin (5.4g)')], max_length=20, verbose_name='format type')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packager', models.CharField(blank=True, choices=[('tyler', 'Tyler'), ('ron', 'Ron'), ('chris', 'Chris'), ('shea', 'Shea'), ('ian', 'Ian'), ('brandon', 'Brandon')], max_length=100, null=True, verbose_name='name of brewer')),
                ('packaging_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('brewing_event', models.ForeignKey(blank=True, help_text='BrewingEvent associated with this packaging event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='brewing.BrewingEvent', verbose_name='Select a brew to package')),
            ],
            options={
                'verbose_name': 'Packaging Event',
            },
        ),
        migrations.CreateModel(
            name='PackagedFormat',
            fields=[
                ('format_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packaging.Format')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total packaged quantity for this format.', max_digits=10, verbose_name='quantity')),
            ],
            bases=('packaging.format',),
        ),
        migrations.AddField(
            model_name='packagingevent',
            name='formats',
            field=models.ManyToManyField(blank=True, help_text='Zero or more formats', null=True, to='packaging.PackagedFormat'),
        ),
    ]
