# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Trade Name')),
            ],
        ),
        migrations.CreateModel(
            name='BrewingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateField(default=django.utils.timezone.now)),
                ('brewed_beer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='packaging.Beer')),
            ],
        ),
        migrations.CreateModel(
            name='Gyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=7, verbose_name='#')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_date', models.DateField(default=django.utils.timezone.now)),
                ('packaged_beer_format', models.CharField(blank=True, choices=[('12oz/CS', '12oz/CS'), ('16oz/CS', '16oz/CS'), ('375ml/CS', '375ml/CS'), ('500ml/CS', '500ml/CS'), ('750ml/CS', '750ml/CS'), ('1/6bbl', '1/6bbl'), ('1/4bbl', '1/4bbl'), ('1/2bbl', '1/2bbl'), ('50l', '50l'), ('Firkin (10.8g)', 'Firkin (10.8g)'), ('Pin (5.4g)', 'Pin (5.4g)')], default='12oz/CS', max_length=20, verbose_name='Format')),
                ('packaged_quantity', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('packaged_beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='brewingevent',
            name='gyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.Gyle'),
        ),
        migrations.AddField(
            model_name='brewingevent',
            name='gyle2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='packaging.Gyle'),
        ),
    ]
