# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewingevent',
            name='brewed_beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.Beer'),
        ),
    ]
