# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hop',
        ),
    ]
