# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_auto_20180117_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='brewingevent',
            name='brewed_beer',
        ),
        migrations.RemoveField(
            model_name='brewingevent',
            name='gyle',
        ),
        migrations.RemoveField(
            model_name='brewingevent',
            name='gyle2',
        ),
        migrations.AlterModelOptions(
            name='packagingevent',
            options={'verbose_name': 'Packaging Event'},
        ),
        migrations.AlterModelOptions(
            name='packagingformat',
            options={'verbose_name': 'Packaging Format'},
        ),
        migrations.AlterField(
            model_name='packagingevent',
            name='packaged_beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewing.Beer'),
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.DeleteModel(
            name='BrewingEvent',
        ),
        migrations.DeleteModel(
            name='Gyle',
        ),
    ]
