# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingevent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
