# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0002_brewingevent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.CharField(max_length=5, unique=True, verbose_name='Batch Number(s)'),
        ),
    ]
