# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0003_auto_20180208_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewingevent',
            name='brewer',
            field=models.CharField(choices=[('sean', 'Sean'), ('shea', 'Shea'), ('ian', 'Ian'), ('ron', 'Ron'), ('brandon', 'Brandon')], max_length=100, verbose_name='name of brewer'),
        ),
    ]
